
@section('newproject', 'Create a New Project')
@section('newtask', 'Create a New Task')
@section('newiteration', 'Create a New Iteration')
@section('newacpttest', 'Create a New Acceptance Test')
@section('newfeature', 'Create a New Feature')
@section('editproject', 'Editing a Project')
@section('edittask', 'Editing a Task')
@section('edititeration', 'Editing an Iteration')
@section('editacpttest', 'Editing an Acceptance Test')
@section('editfeature', 'Editing a Feature')